### ISSUE TITLE
Option for using Layout instead of Language

### ISSUE THREAD

**Issue by Osyx** [siropkin/kursor#4] opened 2024-07-10 12:52 UTC
I would like the option to show keyboard layouts on cursor. 

I have the same language but use different layouts, which makes the Kursor language info somewhat irrelevant. 
![image](https://github.com/siropkin/kursor/assets/9387558/b62818d7-4de5-4f03-888a-eb6be938280b)
![image](https://github.com/siropkin/kursor/assets/9387558/393e0d13-903e-43a2-9faa-efecaba09a7d)

Would be awesome if there was an option to have the cursor info instead show the layout instead of language.
So in my case it would say SV and US, or similar, instead of EN for both.

A bonus would be if there was a “default layout” and “show default layout” option as well.

**Comment by siropkin** [comment] 2024-07-14 22:47
I like that idea and have started working on it and I want to share what I have locally and ask you a few questions / receive your feedback.
So at my current local version I added two new params:
- Default layout (win only)
- Show keyboard layout (win only)
![image](https://github.com/user-attachments/assets/a91cf9a9-3019-4155-ac18-595fd3a17c0f)

And this is how it indicates default language but not default layout (language-layout):
![image](https://github.com/user-attachments/assets/30a77da3-8ae8-44d0-a38d-471449c33727)

And this is how non default language (as before):
![image](https://github.com/user-attachments/assets/341ad725-d450-4666-95fe-5e99ab3272a0)

But then I reread your idea and especially this part:
> instead show the layout instead of language

So you think it's better to get rid of "Default language" and use only "Default layout"?
I mean I like it just want to make sure I get it right and I need to imagine how all will works.

**Comment by siropkin** [comment] 2024-07-14 22:48
And i want to simplify it for users without additional layouts (with only one layout)

**Comment by siropkin** [comment] 2024-07-14 22:54
Or maybe it should be just setting like "Use keyboard layout instead of keyboard language" (checkbox) and that's it

**Comment by Osyx** [comment] 2024-07-14 23:49
> Or maybe it should be just setting like "Use keyboard layout instead of keyboard language" (checkbox) and that's it

Yea, I like that idea, makes it simple for people who only uses language, and simple for people who use different layouts. Especially considering:

> So you think it's better to get rid of "Default language" and use only "Default layout"?

With the checkbox, yes! I don't think language matters if the layout is different, since the IDE doesn't show autocomplete info, as far as I know. And the reason to see the language info normally is that it also changes the layout, right?

However, with that said, some users might have different languages with different layouts, and in that case maybe they would like to see both? Though I'm not sure for what purpose. 
In that case, if you check the "Use keyboard layout" option, then perhaps a checkbox for "Also show language info" might be warranted? But that also might be catering for something that people don't use, so I'm unsure.

**Comment by Osyx** [comment] 2024-07-14 23:56
Btw, is there a reason why it is Win only? Haven't used macOS all that much, but on my Linux installations I usually tend to also use different layouts, rather than language.

**Comment by siropkin** [comment] 2024-07-15 13:31
Yeah, you are right, it should not be Win only. I did it for Win in the first place 'cause different OS have different ways to get keyboard layout and I'm a Win user so it was easier to do it first.
Ok, I need time to implement this idea in life.

**Comment by Osyx** [comment] 2024-07-15 14:19
No worries, take your time, very glad that you responded so quickly!

**Comment by siropkin** [comment] 2024-07-23 15:05
In the end, I decided to simplify the solution and always take keyboard layout into account (meaning, now Kursor always indicates keyboard layout priop to keyboard language).
I also improved plugin settings and:
- changed "Default language" settings component from prefilled combobox to input (meaning, user can put any value there)
- added new button "Detect Keyboard Layout" which allows to detect and prefill "Default language" if user do not know what to put there

All this will be in Kursor v1.1.0 which is now in JetBrains' review (~2 days).

**Comment by Osyx** [comment] 2024-07-23 17:53
Awesome, great work, thank you!

**Comment by siropkin** [comment] 2024-07-23 19:36
@Osyx Plugin v1.1.0 published 🎉 Please try it and tell me what do you think

**Comment by Osyx** [comment] 2024-07-24 00:14
Nice! Though not sure if I'm missing something, but for me, it still follows the language:

![image](https://github.com/user-attachments/assets/8b0ab4e7-3957-495d-9824-423b921477ab)
![image](https://github.com/user-attachments/assets/cb2a79ae-d52e-46da-840a-12b2983e5702)
![image](https://github.com/user-attachments/assets/3c95af06-c518-4af5-a788-165d0d03ca08)

My windows settings, if you want to try to reproduce:
![image](https://github.com/user-attachments/assets/47c18970-ec3b-428e-8b8d-ba90bbc7df1a)
The GB entry:
![image](https://github.com/user-attachments/assets/6b529c46-7ee6-4914-aab7-62988877a95d)

Sidenote, the Swedish entry has no layouts assigned, hence why it does not show up in the layout bar, so no need to have it in the list to reproduce. JP is skippable as well, since that one does show up as expected.

**Comment by siropkin** [comment] 2024-07-24 13:31
Thank you for the info, it helped me to reproduce the issue locally! Looks like standard Java func does not return info about the current keyboard type. I'll try to find a solution

**Comment by siropkin** [comment] 2024-07-24 14:12
I'll leave this info here. It looks like we can get keyboard type / input method with this Windows command ` Get-WinUserLanguageList` but how to get current input method and method names is not clear yet:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/92a80d1f-7d58-4581-b16b-52e9a1a7c683">

**Comment by siropkin** [comment] 2024-07-24 17:30
Another interesting article: https://www.kbdedit.com/manual/admin_deploy.html

**Comment by siropkin** [comment] 2024-07-24 19:37
Ok, at the end of the day looks like I found a possible solution (for Win) and the result code will be something like this:
```kotlin
    private fun getWindowsKeyboardLayout(): KeyboardLayout {
        val user32 = User32.INSTANCE
        val fgWindow: WinDef.HWND = user32.GetForegroundWindow() // Get the handle of the foreground window
        val threadId = user32.GetWindowThreadProcessId(fgWindow, null) // Get the thread ID of the foreground window
        val hkl: HKL = user32.GetKeyboardLayout(threadId) // Get the keyboard layout for the thread

        val layoutId = hkl.pointer.toString() // Use the pointer to get the layout ID (first symbols is Keyboard layout ID, last is Language ID)
        val locale = Locale.forLanguageTag(layoutId) // Convert the layout ID to a Locale <<<<< not working

        return KeyboardLayout(locale.country, locale.language)
    }
```

with this code I will get this in `layoutId` and first symbols is Keyboard layout ID, last is Language ID
```
us - 04090409
sv - 041d0409
ru - 04190419
```

all I need to do now is to understand how to convert it to country/language/input type because `val locale = Locale.forLanguageTag(layoutId)` not working right now.

I hope I'm close.

**Comment by siropkin** [comment] 2024-07-25 15:08
Alright alright alright, looks like i did it! Now iäm testing the changes and if all good will push it to the marketplace soon

![kursor](https://github.com/user-attachments/assets/1e92f9d6-b37e-4f68-b1e3-141857ac4d93)

**Comment by Osyx** [comment] 2024-07-25 15:29
Awesome, good job!

**Comment by siropkin** [comment] 2024-07-25 18:48
Plugin v1.1.1 published, please try it and tell me what do you think

**Comment by Osyx** [comment] 2024-07-25 20:17
It works perfectly, thank you!

**Closed** 2024-07-25 20:25 UTC
