### ISSUE TITLE
Plugin configuration not found

### ISSUE THREAD

**Issue by ZHOUXING1997** [siropkin/kursor#8] opened 2024-07-24 03:25 UTC
![image](https://github.com/user-attachments/assets/383d3194-4fb9-4d80-b8e6-133bc97d3696)

![image](https://github.com/user-attachments/assets/92bef958-86c4-4152-875d-47d984d50f3e)

1. I installed the plug-in, but couldn't find the relevant configuration.

2. My input method comes with English and Chinese, and I did not switch the input type through the system language. It seems that this situation cannot be detected by the plug-in.
  -  I tested and found that the plug-in monitors the input method switching shortcut keys, not the actual language status.
  - This is my input method： https://pinyin.sogou.com/mac

**Comment by siropkin** [comment] 2024-07-24 14:15
Thank you for the info and it's very interesting! What kind of JetBrains product are you using? I'll try to reproduce it locally

**Comment by siropkin** [comment] 2024-07-24 14:23
> InputMethodTips (READ/WRITE). A list of input method Tablet Input Panel (TIP) strings that are enabled for this language. The enabled Input methods are listed in the format Language ID: Keyboard layout ID.

Keyboard layout ID: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11

**Comment by ZHOUXING1997** [comment] 2024-07-25 02:15
> 谢谢你的信息，这很有趣！你使用的是哪种 JetBrains 产品？我会尝试在本地重现它

goland

**Comment by ZHOUXING1997** [comment] 2024-07-25 02:17
> > InputMethodTips（读/写）。针对此语言启用的输入法平板电脑输入面板 (TIP) 字符串列表。启用的输入法以“语言 ID：键盘布局 ID”格式列出。
> 
> 键盘布局 ID：[https ://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11)

I use a mac, not windows

**Comment by siropkin** [comment] 2024-07-26 18:49
I know it could be a big ask but I would appreciate if you would be able to test unreleased yet version 1.2.0 in which I moved plugin settings to Tools (`File` > `Settings` > `Tools` > `Kursor`):
![image](https://github.com/user-attachments/assets/78cdbf0a-10fb-43d0-8d5f-721b7c4df938)

To install plugin from file pls do this: go to Plusings and click on Settings icon on the right and choose "Install plugin from disk"
![image](https://github.com/user-attachments/assets/364fe0a0-9871-483e-af12-fb49ef3e794e)

Unreleased  plugin attached:
[Kursor-1.2.0.zip](https://github.com/user-attachments/files/16395628/Kursor-1.2.0.zip)

**Comment by ZHOUXING1997** [comment] 2024-07-29 02:22
> 未发布的插件附加： [Kursor-1.2.0.zip](https://github.com/user-attachments/files/16395628/Kursor-1.2.0.zip)

I installed version 1.20 and the configuration has been shown normally

**Comment by siropkin** [comment] 2024-07-29 13:31
Great, thank you! So the next task is to detect language...

**Comment by ZHOUXING1997** [comment] 2024-07-30 02:24
The input method I use comes with its own Chinese/English input language, so you may need to adapt some things depending on the input method.
It feels like this is not an easy thing to do, nor is it necessary.

**Comment by siropkin** [comment] 2024-07-30 10:59
> The input method I use comes with its own Chinese/English input language, so you may need to adapt some things depending on the input method. It feels like this is not an easy thing to do, nor is it necessary.

No problem, at least I will try to solve it. I just need time

**Comment by siropkin** [comment] 2024-07-31 13:41
I have good news: looks like I did it - I added support of Sogou Pinyin Method for macOS.

Please try this new not released version and tell me what do you think:
[Kursor-1.3.0.zip](https://github.com/user-attachments/files/16442582/Kursor-1.3.0.zip)

I display that method as "CH". Is it correct?

**Comment by ZHOUXING1997** [comment] 2024-08-01 02:56
> I have good news: looks like I did it - I added support of Sogou Pinyin Method for macOS.
> 
> Please try this new not released version and tell me what do you think: [Kursor-1.3.0.zip](https://github.com/user-attachments/files/16442582/Kursor-1.3.0.zip)
> 

I tried it and it can recognize this input method. Awesome, bro!

But the new problem is: this input method can switch the input language by itself, but I have not found how to obtain the status of the input method language, and there is no way to provide you with relevant help.

It may be that the Mac computer or the input method does not have the relevant API capabilities.

> I display that method as "CH". Is it correct?

Change it to 'ZH'.

For this, I think can make a configuration, read the input method currently enabled on the system in the settings, and then make a mapping, so that don't have to worry about what to display.

**Comment by ZHOUXING1997** [comment] 2024-08-01 02:57
I think this issue can be ended here, because adapting this an input method has taken up a lot of your time.

Thank you very much, brother. Praise you!

**Comment by siropkin** [comment] 2024-08-01 13:43
> Change it to 'ZH'.

Done

> For this, I think can make a configuration, read the input method currently enabled on the system in the settings, and then make a mapping, so that don't have to worry about what to display.

Great idea, I want to do that! This is the ticket for that: https://github.com/siropkin/kursor/issues/14

> I think this issue can be ended here, because adapting this an input method has taken up a lot of your time.

Ok, thank you. I'll close this issue and publish the new version.
If you think we need to go back to that issue in the future, please open a new ticket and we will try to find a solution.

Thank you for the help!

**Closed** 2024-08-01 14:25 UTC
